aws_primary_region     = "ca-central-1"
aws_secondary_region   = "us-west-1"
s3_bucket_name         = "thefoodexplorer-data"
s3_bucket_name_state   = "thefoodexplorer-state"
subscribers_table_name = "the-food-explorer-subscribers"
source_email_address   = "me@backtorod.com"
schedule_expression    = "cron(0 8 * * ? *)"
